/* Generated By:JavaCC: Do not edit this line. ExpressionParserConstants.java */
package nts.uk.shr.com.fomula;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParserConstants {

	/** End of File. */
	int EOF = 0;
	/** RegularExpression Id. */
	int EOL = 5;
	/** RegularExpression Id. */
	int SEPERATOR = 6;
	/** RegularExpression Id. */
	int LBRACKET = 7;
	/** RegularExpression Id. */
	int RBRACKET = 8;
	/** RegularExpression Id. */
	int PLUS = 9;
	/** RegularExpression Id. */
	int MINUS = 10;
	/** RegularExpression Id. */
	int MULTIPLY = 11;
	/** RegularExpression Id. */
	int DIVIDE = 12;
	/** RegularExpression Id. */
	int POWER = 13;
	/** RegularExpression Id. */
	int ROUND = 14;
	/** RegularExpression Id. */
	int FLOOR = 15;
	/** RegularExpression Id. */
	int CEIL = 16;
	/** RegularExpression Id. */
	int MAX = 17;
	/** RegularExpression Id. */
	int MIN = 18;
	/** RegularExpression Id. */
	int CONDITION = 19;
	/** RegularExpression Id. */
	int AND = 20;
	/** RegularExpression Id. */
	int OR = 21;
	/** RegularExpression Id. */
	int LARGER_OR_EQUALS = 22;
	/** RegularExpression Id. */
	int LESSER_OR_EQUALS = 23;
	/** RegularExpression Id. */
	int LARGER = 24;
	/** RegularExpression Id. */
	int LESSER = 25;
	/** RegularExpression Id. */
	int EQUALS = 26;
	/** RegularExpression Id. */
	int NOT_EQUALS = 27;
	/** RegularExpression Id. */
	int CONSTANT = 28;
	/** RegularExpression Id. */
	int DIGIT = 29;
	/** RegularExpression Id. */
	int DECIMAL = 30;

	/** Lexical state. */
	int DEFAULT = 0;

	/** Literal token values. */
	String[] tokenImage = { "<EOF>", "\" \"", "\"\\u7e32\\ufffd\"", "\"\\r\"", "\"\\t\"", "\"\\n\"", "<SEPERATOR>",
			"<LBRACKET>", "<RBRACKET>", "<PLUS>", "<MINUS>", "<MULTIPLY>", "<DIVIDE>", "<POWER>", "<ROUND>", "<FLOOR>",
			"<CEIL>", "<MAX>", "<MIN>", "<CONDITION>", "<AND>", "<OR>", "\"\\u7ad5\\uff67\"", "\"\\u7ad5\\uff66\"",
			"<LARGER>", "<LESSER>", "<EQUALS>", "\"\\u7ad5\\ufffd\"", "<CONSTANT>", "<DIGIT>", "<DECIMAL>", };

}
